$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'

language:
  - en
  - es

ignorePaths:
  # default ignores
  - '.idea/**'
  - '.vscode/**'
  - '.dictionaries/**'
  - 'LICENSE'
  - '.cspell.config.yaml'
  - 'public/data/**'
  - '**.svg'
  - 'Conocimientos.astro'

dictionaryDefinitions:
  - name: 'project-words'
    path: './.dictionaries/project-words.txt'
  - name: 'spanish'
    path: './.dictionaries/spanish.txt'

dictionaries:
  - 'project-words'
  - 'spanish'

import:
  - '@cspell/dict-es-es/cspell-ext.json'

words: []
ignoreWords: []
useGitignore: true
# enabled: false

overrides:
  # Markdown (.md) → EN + ES
  - filename: '**/*.md'
    language:
      - en
      - es
    allowCompoundWords: true
